.nh
.TH "BB" "1" "Mar 2026" "bb" "Bitbucket CLI"

.SH NAME
bb-deployment-environment-variable-edit - Edit a deployment environment variable


.SH SYNOPSIS
\fBbb deployment environment variable edit  [flags]\fP


.SH DESCRIPTION
Edit a Bitbucket deployment environment variable by key or UUID. By default the existing secured flag is preserved unless --secured true or --secured false is provided.


.SH OPTIONS
\fB--environment\fP=""
	Deployment environment reference as a name, slug, or UUID

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for edit

.PP
\fB--host\fP=""
	Bitbucket host to use

.PP
\fB--jq\fP=""
	Filter JSON output using a jq expression

.PP
\fB--json\fP[=""]
	Output JSON with the specified comma-separated fields, or '*' for all fields

.PP
\fB--key\fP=""
	Override the deployment variable key

.PP
\fB--repo\fP=""
	Bitbucket repository target as , /, or a repository URL

.PP
\fB--secured\fP=""
	Set secured to true or false; defaults to the existing value

.PP
\fB--value\fP=""
	Deployment variable value

.PP
\fB--value-file\fP=""
	Read the deployment variable value from a file, or '-' for stdin

.PP
\fB--workspace\fP=""
	Optional workspace slug used only to disambiguate a bare repository target


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-prompt\fP[=false]
	Do not prompt for missing input, even in an interactive terminal


.SH EXAMPLE
.EX
  bb deployment environment variable edit APP_ENV --repo workspace-slug/pipelines-repo-slug --environment test --value staging
  bb deployment environment variable edit '{variable-uuid}' --repo workspace-slug/pipelines-repo-slug --environment test --secured true --json '*'
.EE


.SH SEE ALSO
\fBbb-deployment-environment-variable(1)\fP


.SH HISTORY
14-Mar-2026 Auto generated by spf13/cobra
