.nh
.TH "BB" "1" "Mar 2026" "bb" "Bitbucket CLI"

.SH NAME
bb-pipeline-variable-create - Create a repository pipeline variable


.SH SYNOPSIS
\fBbb pipeline variable create [flags]\fP


.SH DESCRIPTION
Create a repository pipeline variable


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--host\fP=""
	Bitbucket host to use

.PP
\fB--jq\fP=""
	Filter JSON output using a jq expression

.PP
\fB--json\fP[=""]
	Output JSON with the specified comma-separated fields, or '*' for all fields

.PP
\fB--key\fP=""
	Pipeline variable key

.PP
\fB--repo\fP=""
	Bitbucket repository target as , /, or a repository URL

.PP
\fB--secured\fP[=false]
	Mark the variable as secured

.PP
\fB--value\fP=""
	Pipeline variable value

.PP
\fB--value-file\fP=""
	Read the pipeline variable value from a file, or '-' for stdin

.PP
\fB--workspace\fP=""
	Optional workspace slug used only to disambiguate a bare repository target


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-prompt\fP[=false]
	Do not prompt for missing input, even in an interactive terminal


.SH EXAMPLE
.EX
  bb pipeline variable create --repo workspace-slug/pipelines-repo-slug --key CI_TOKEN --value-file secret.txt --secured
  printf 'token-value\\n' | bb pipeline variable create --repo workspace-slug/pipelines-repo-slug --key CI_TOKEN --value-file - --json '*'
  bb pipeline variable create --repo workspace-slug/pipelines-repo-slug --key APP_ENV --value production
.EE


.SH SEE ALSO
\fBbb-pipeline-variable(1)\fP


.SH HISTORY
14-Mar-2026 Auto generated by spf13/cobra
