.nh
.TH "BB" "1" "Mar 2026" "bb" "Bitbucket CLI"

.SH NAME
bb-pipeline-variable-edit - Edit a repository pipeline variable


.SH SYNOPSIS
\fBbb pipeline variable edit  [flags]\fP


.SH DESCRIPTION
Edit a Bitbucket repository pipeline variable by key or UUID. By default the existing secured flag is preserved unless --secured true or --secured false is provided.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for edit

.PP
\fB--host\fP=""
	Bitbucket host to use

.PP
\fB--jq\fP=""
	Filter JSON output using a jq expression

.PP
\fB--json\fP[=""]
	Output JSON with the specified comma-separated fields, or '*' for all fields

.PP
\fB--key\fP=""
	Override the pipeline variable key

.PP
\fB--repo\fP=""
	Bitbucket repository target as , /, or a repository URL

.PP
\fB--secured\fP=""
	Set secured to true or false; defaults to the existing value

.PP
\fB--value\fP=""
	Pipeline variable value

.PP
\fB--value-file\fP=""
	Read the pipeline variable value from a file, or '-' for stdin

.PP
\fB--workspace\fP=""
	Optional workspace slug used only to disambiguate a bare repository target


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-prompt\fP[=false]
	Do not prompt for missing input, even in an interactive terminal


.SH EXAMPLE
.EX
  bb pipeline variable edit CI_TOKEN --repo workspace-slug/pipelines-repo-slug --value-file secret.txt --secured true
  bb pipeline variable edit '{uuid}' --repo workspace-slug/pipelines-repo-slug --key APP_ENV --value staging --json '*'
  bb pipeline variable edit APP_ENV --repo workspace-slug/pipelines-repo-slug --value production
.EE


.SH SEE ALSO
\fBbb-pipeline-variable(1)\fP


.SH HISTORY
14-Mar-2026 Auto generated by spf13/cobra
