.nh
.TH "BB" "1" "Mar 2026" "bb" "Bitbucket CLI"

.SH NAME
bb-pr-task-create - Create a task on a pull request


.SH SYNOPSIS
\fBbb pr task create  [flags]\fP


.SH DESCRIPTION
Create a Bitbucket pull request task using --body, --body-file, or --body-file - for stdin. Use --comment to attach the task to a specific pull request comment when Bitbucket Cloud supports that linkage.


.SH OPTIONS
\fB--body\fP=""
	Task body text

.PP
\fB--body-file\fP=""
	Read the task body from a file, or '-' for stdin

.PP
\fB--comment\fP=""
	Optional pull request comment as a numeric ID or Bitbucket pull request comment URL

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for create

.PP
\fB--host\fP=""
	Bitbucket host to use

.PP
\fB--jq\fP=""
	Filter JSON output using a jq expression

.PP
\fB--json\fP[=""]
	Output JSON with the specified comma-separated fields, or '*' for all fields

.PP
\fB--pending\fP[=false]
	Mark the created task as pending

.PP
\fB--repo\fP=""
	Bitbucket repository target as , /, or a repository URL

.PP
\fB--workspace\fP=""
	Optional workspace slug used only to disambiguate a bare repository target


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--no-prompt\fP[=false]
	Do not prompt for missing input, even in an interactive terminal


.SH EXAMPLE
.EX
  bb pr task create 1 --repo workspace-slug/repo-slug --body 'Follow up on review feedback'
  bb pr task create 1 --repo workspace-slug/repo-slug --comment 15 --body-file task.md --json '*'
  bb pr task create https://bitbucket.org/workspace-slug/repo-slug/pull-requests/1 --comment https://bitbucket.org/workspace-slug/repo-slug/pull-requests/1#comment-15 --body 'Handle this thread'
.EE


.SH SEE ALSO
\fBbb-pr-task(1)\fP


.SH HISTORY
14-Mar-2026 Auto generated by spf13/cobra
